name: Render pdf
on:
  push:
    tags:
      - '*'
jobs:
  render-paper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
        # with:
        #   cache-dependency-path: requirements.typ
      - run: mkdir -p dist
      - name: Extract tag name
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: typst compile src/main.typ dist/MathSummary-${{ steps.get_version.outputs.VERSION }}.pdf
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/MathSummary-${{ steps.get_version.outputs.VERSION }}.pdf"
          bodyFile: "CHANGELOG.md"